version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/taskforge
      - JWT_SECRET=2928409a8530b29bd7fc51eb40dbc572
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - taskforge-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - taskforge-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - taskforge-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u root -p example --quiet
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:

networks:
  taskforge-network:
    driver: bridge